### ISSUE TITLE
Add multiple classes?

### ISSUE THREAD

**Issue by chris-dura** [hipstersmoothie/storybook-dark-mode#219]
Is there a way to add multiple classes?

```js
darkMode: {
		current: "light",
		light: myThemeLight,
		dark: myThemeDark,
		lightClass: "my-theme my-theme--light",
		darkClass: "my-theme my-theme--dark",
		classTarget: "html",
		stylePreview: true,
	},
```

This gives an error:

```sh
ndors~main.f4a0d82e8f8bf122d552.manager.bundle.js:44 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('my-theme my-theme--dark') contains HTML space characters, which are not valid in tokens.
    at toggleDarkClass (http://localhost:5280/vendors~main.f4a0d82e8f8bf122d552.manager.bundle.js:44:1698630)
    at updateManager (http://localhost:5280/vendors~main.f4a0d82e8f8bf122d552.manager.bundle.js:44:1699277)
    at Module.<anonymous> (http://localhost:5280/vendors~main.f4a0d82e8f8bf122d552.manager.bundle.js:44:1699871)
    at __webpack_require__ (http://localhost:5280/runtime~main.c35c46b9c170e8c7a963.manager.bundle.js:1:1301)
    at 494 (http://localhost:5280/main.d66d44eb2fd75c955afa.manager.bundle.js:1:531005)
    at __webpack_require__ (http://localhost:5280/runtime~main.c35c46b9c170e8c7a963.manager.bundle.js:1:1301)
    at checkDeferredModules (http://localhost:5280/runtime~main.c35c46b9c170e8c7a963.manager.bundle.js:1:957)
    at Array.webpackJsonpCallback [as push] (http://localhost:5280/runtime~main.c35c46b9c170e8c7a963.manager.bundle.js:1:645)
    at http://localhost:5280/main.d66d44eb2fd75c955afa.manager.bundle.js:1:47
t
```

**Comment by hipstersmoothie** [comment]
Doesn't seem like it! @chris-dura would you want to submit a pr to fix?
