### ISSUE TITLE
4.0.2 "Storybook preview hooks can only be called inside decorators and story functions."

### ISSUE THREAD

**Issue by bcbailey-torus** [hipstersmoothie/storybook-dark-mode#282]
### Summary

After upgrading to version 4.0.2 I am getting the error `Storybook preview hooks can only be called inside decorators and story functions.`

Downgrading to 4.0.1 makes the error goes away.

This is likely related to the changes in #279

### Full error

```
Error: Storybook preview hooks can only be called inside decorators and story functions.
    at invalidHooksError (http://localhost:6006/sb-preview/runtime.js:97:11863)
    at getHooksContextOrThrow (http://localhost:6006/sb-preview/runtime.js:97:12123)
    at useHook (http://localhost:6006/sb-preview/runtime.js:97:12204)
    at useMemoLike (http://localhost:6006/sb-preview/runtime.js:99:209)
    at useRefLike (http://localhost:6006/sb-preview/runtime.js:99:505)
    at useStateLike (http://localhost:6006/sb-preview/runtime.js:99:940)
    at useState (http://localhost:6006/sb-preview/runtime.js:99:1201)
    at useDarkMode (http://localhost:6006/node_modules/.cache/storybook/ee6bf224cd156d2a19aeb1406fef9897dbfe874b3eae8c467c24b2f62e4ecd1a/sb-vite/deps/storybook-dark-mode.js?v=2c4e06dd:8560:51)
    at DarkModeObserver (http://localhost:6006/.storybook/preview.tsx:11:18)
    at renderWithHooks (http://localhost:6006/node_modules/.cache/storybook/ee6bf224cd156d2a19aeb1406fef9897dbfe874b3eae8c467c24b2f62e4ecd1a/sb-vite/deps/chunk-ILFQ7OTE.js?v=2c4e06dd:11548:26)
```

### Reference

My storybook `.storybook/preview.tsx` for reference:

```
import { useDarkMode } from 'storybook-dark-mode'
import { useColorScheme } from '@mui/material/styles'
import { useEffect } from 'react'
import { Experimental_CssVarsProvider as CssVarsProvider } from '@mui/material/styles'
import CssBaseline from '@mui/material/CssBaseline'

const DarkModeObserver = () => {
    const isDark = useDarkMode()
    const { setMode } = useColorScheme()
    useEffect(() => {
        if (isDark) {
            setMode('dark')
        } else {
            setMode('light')
        }
    }, [isDark])
    return null
}

const preview: Preview = {
    // ...
    decorators: [
        (Story) => (
            <CssVarsProvider theme={myThemeV1}>
                <DarkModeObserver />
                <CssBaseline />
                <Story />
            </CssVarsProvider>
        ),
    ],
}

export default preview
```

**Comment by grubersjoe** [comment]
If I understand #279 correctly this change was necessary to be compatible with `@storybook/preview-api`, correct? My use case was to dynamically change the theme of the docs container in [`preview.tsx`](https://github.com/grubersjoe/react-activity-calendar/blob/bd88d9bca7fa08ad82d0fa3fe36da49342fa3d0b/.storybook/preview.tsx#L20
):

```tsx
// .storybook/preview.tsx
const Container = (props: DocsContainerProps) => (
  <DocsContainer
    {...props}
    theme={{
      ...common,
      ...(useDarkMode() ? themes.dark : themes.light), // <<<
    }}
  />
);
```

Unfortunately, this broke with `storybook-dark-mode@4.0.2`. Does someone have an idea what to do about this? Is this hook simply no longer supported inside `preview.tsx`? Had the terrible idea to use a MutationObserver on the body class to work around this issue:

https://github.com/grubersjoe/react-activity-calendar/blob/main/.storybook/preview.tsx

I don't know why Storybook did these changes but they feel quite limiting =/.

**Comment by valpioner** [comment]
I can also reproduce this runtime error. It completely breaks a way we provide a theme for our storybook docs. Can someone please fix it or suggest another way to change docs theme?

```ts
// preview.ts
...
import { MyDocsContainer2 } from './docsContainer';

const preview: Preview = {
  parameters: {
    docs: {
      container: myDocsContainer
```

```tsx
// myDocsContainer.tsx
...
import { useDarkMode } from 'storybook-dark-mode';

export const MyDocsContainer = (props: PropsWithChildren<DocsContainerProps>) => (
  <DocsContainer context={props.context} theme={useDarkMode() ? themes.dark : themes.light}>
    {props.children}
  </DocsContainer>
);
```

**Comment by skaneprime** [comment]
Facing same problem for dark mode in docs 
```tsx
    docs: {
      container: (props) => {
        const isDark = useDarkMode();
        const currentProps = { ...props };
        currentProps.theme = isDark ? themes.dark : themes.light;
        return React.createElement(DocsContainer, currentProps);
      },
    },
```
![image](https://github.com/hipstersmoothie/storybook-dark-mode/assets/50551032/eba6f479-0282-4d8f-a67c-82c8f707eeee)

**Comment by skaneprime** [comment]
Found workaround for dark mode

```tsx

const preview: Preview = {
    docs: {
      container: (props: {
        children: React.ReactNode;
        context: DocsContextProps;
        theme?: ThemeVars;
      }) => {
        // eslint-disable-next-line react-hooks/rules-of-hooks
        const [isDark, setDark] = React.useState(true);
        props.context.channel.on(DARK_MODE_EVENT_NAME, (state) =>
          setDark(state)
        );
        const currentProps = { ...props };
        currentProps.theme = isDark ? themes.dark : themes.light;
        return <DocsContainer {...currentProps} />;
      },
}
```

**Comment by skaneprime** [comment]
More a bit cleaner pragmatic solution
in preview.tsx 
```tsx
const MyDocsContainer = (props: {
        children: React.ReactNode;
        context: DocsContextProps;
        theme?: ThemeVars;
      }) => {
        const [isDark, setDark] = React.useState(true);

        React.useEffect(() => {
          props.context.channel.on(DARK_MODE_EVENT_NAME, setDark);

          return () =>
            props.context.channel.removeListener(DARK_MODE_EVENT_NAME, setDark);
        }, [props.context.channel]);

        return (
          <DocsContainer
            {...props}
            theme={isDark ? themes.dark : themes.light}
          />
        );
      }
```

**Comment by grubersjoe** [comment]
I mean it's a hack, but that's a lot better than the abomination I came up with spontaneously :D.

**Comment by TheMikeyRoss** [comment]
How do we access the current color mode in a single story?

**Comment by damisparks** [comment]
I am having the same issue.
```
"storybook": "^8.2.3",
"storybook-dark-mode": "^4.0.2",
```
<img width="811" alt="Screenshot 2024-07-19 at 11 22 57" src="https://github.com/user-attachments/assets/d322c687-72b3-44b5-8ff1-5d1b038d42f6">

Any suggestions here?

**Comment by damisparks** [comment]
> More a bit cleaner pragmatic solution in preview.tsx
> 
> ```tsx
> const MyDocsContainer = (props: {
>         children: React.ReactNode;
>         context: DocsContextProps;
>         theme?: ThemeVars;
>       }) => {
>         const [isDark, setDark] = React.useState(true);
> 
>         React.useEffect(() => {
>           props.context.channel.on(DARK_MODE_EVENT_NAME, setDark);
> 
>           return () =>
>             props.context.channel.removeListener(DARK_MODE_EVENT_NAME, setDark);
>         }, [props.context.channel]);
> 
>         return (
>           <DocsContainer
>             {...props}
>             theme={isDark ? themes.dark : themes.light}
>           />
>         );
>       }
> ```

@skaneprime  Although this solution works. However, it creates some flickering when switching between docs.

**Comment by valpioner** [comment]
> > More a bit cleaner pragmatic solution in preview.tsx
> > ```tsx
> > const MyDocsContainer = (props: {
> >         children: React.ReactNode;
> >         context: DocsContextProps;
> >         theme?: ThemeVars;
> >       }) => {
> >         const [isDark, setDark] = React.useState(true);
> > 
> >         React.useEffect(() => {
> >           props.context.channel.on(DARK_MODE_EVENT_NAME, setDark);
> > 
> >           return () =>
> >             props.context.channel.removeListener(DARK_MODE_EVENT_NAME, setDark);
> >         }, [props.context.channel]);
> > 
> >         return (
> >           <DocsContainer
> >             {...props}
> >             theme={isDark ? themes.dark : themes.light}
> >           />
> >         );
> >       }
> > ```
> 
> @skaneprime Although this solution works. However, it creates some flickering when switching between docs.

Is there maybe a way to cache the current value and use it instead of a hardcoded `true`?

**Comment by Mookiies** [comment]
By using the channel from preview you can make a hook which can be used in both docs container and decorator

```ts
import { addons } from '@storybook/preview-api';

const channel = addons.getChannel();

function useDarkMode() {
  const [isDark, setDark] = React.useState(false);

  React.useEffect(() => {
    channel.on(DARK_MODE_EVENT_NAME, setDark);
    return () => channel.off(DARK_MODE_EVENT_NAME, setDark);
  }, [channel, setDark]);

  return isDark;
}
```

Based off [this section of the readme](https://github.com/hipstersmoothie/storybook-dark-mode?tab=readme-ov-file#events)

**Comment by martinsik** [comment]
Based on your suggestions, to avoid the initial blinking when switching to dark mode or reloading a page already in dark mode, you can store the setting in `localStorage` and then use the value to initialise `useState`. It's an ugly hack but it works and hopefully this will be resolved soon.

```ts
const [isDark, setDark] = useState(isDarkModeEnabled());

useEffect(() => {
	channel.on(DARK_MODE_EVENT_NAME, state => {
		setDarkModeEnabled(state);
		setDark(state);
	});

	return () => channel.removeListener(DARK_MODE_EVENT_NAME, setDark);
}, []);

// ...

const LOCAL_STORAGE_KEY = '_tmp-dark-mode-hack';

export const isDarkModeEnabled = () => Boolean(localStorage.getItem(LOCAL_STORAGE_KEY));

export const setDarkModeEnabled = (enabled: boolean) =>
	enabled
		? localStorage.setItem(LOCAL_STORAGE_KEY, '1')
		: localStorage.removeItem(LOCAL_STORAGE_KEY);
```
